### PR TITLE
Refactor citations and add Endnote fields

### PR DESCRIPTION
**Pull request by jlevnhv**
In order to add additional Endnote fields, it was important to refactor the way citations are created. Now, a couple of functions have been added in order to format the MARC objects in a reasonable way which can then be used in multiple formats (Refworks, Endnote, etc.). May also be used to enable RIS in the future.

These functions are:

`to_object`: Creates a Hash object with various fields like `doc['isbn']` and `doc['author']` which can be used to easily grab necessary data for various citation formats without having to worry about specific MARC implemtnation
`record_to_array`: Takes a specific MARC field (i.e., '020.a') and turns it into an array of 0 or more strings with the MARC data requested. Could return a 0 length array, or however many objects it finds, depending on the MARC field. Called by `to_object`.

Now, the `export_as_endnote()` function will use the Hash created by `to_object` to refer to various citation fields (i.e. mapping %A to `doc['author']`). 

Test Steps:

1. Point `search-frontend` to the Pull Request Git Branch and run a `bundle install`.
2. Download Endnote citations from the following resources and verify additional fields look correct:
- http://localhost:3000/catalog/13781969
- http://localhost:3000/catalog/6483822
- http://localhost:3000/catalog/8165298
3. Verify everything looks good in Endnote.
4. Run tests from quick-search frontend:
- Login to Vagrant box
- CD into your Quicksearch folder
- Run command: `rspec ../blacklight-marc/spec/lib/marc_export.rb` and verify all tests complete
(This may involve you having to clone the gem into the Vagrant box if you haven't already)

Once this is done, we can do the following to put these changes into Quicksearch Production:

1. Merge `add_fields` into `test`
2. Test Quicksearch with `test` branch of this Gem
3. Merge into `prod`
4. Change Quicksearch to have `blacklight-marc` gem point to this Repo in `prod`
5. Do PR on this change with additional testing

After that, we can look into supporting additional formats.

### CODE REVIEW

**Comment by ksprague25** [comment]
[(42)Include Metadata: all necessary metadata fields should be included in export from Refworks, Endnote, Zotero, and Mendeley. [45]](https://trello.com/c/RdB1DUOa/152-42include-metadata-all-necessary-metadata-fields-should-be-included-in-export-from-refworks-endnote-zotero-and-mendeley-45)

**Comment by mikeapp** [comment]
The first comparison in the unit test fails (line 697 in `marc_export_spec.rb`) but was apparently magic even to the developer who wrote it, so let's remove it.

The other issue is that the existing tests seem to expect a trailing space.  @ksprague25 is there some library convention at work here, or should we adjust the test to match our data?

```
  1) Blacklight::Solr::Document::MarcExport export_as_endnote should export_correctly
     Failure/Error: expect(endnote_entries["D"]).to eq(Set.new(["p2001. "]))
     
       expected: #<Set: {"p2001. "}>
            got: #<Set: {"p2001."}>
```

**Comment by mikeapp** [comment]
Made a commit to fix up the tests.  Note that one issue in the tests is that field 0 was not being populated.   The test expected it to exist and have the string value `Generic`.   According to [documentation that I found online](http://www.msg.ucsf.edu/agard/Software/EndNote%20X1/EndNote%20X1.app/Contents/Resources/EndNote%20X1%20Help/07Import/Creating_a_TaggedENImprtFl.htm) Endnote will attempt to determine the type based on the fields provided.   So `I without B, J, or R` will result in `Book`.  But there are other types (`Map`, `Manuscript`, etc.) that could be used.

**Comment by ksprague25** [comment]
Note that the test record 13781969 can't be testing unless pointing at the solr core on search-uat

**Comment by ksprague25** [comment]
6483822 - the addition of the 490 field does not work.  Looks like the %J may never have worked.  According to the summon_citation-export gem, the mapping should be to %S?

Also the scale is not coming in for the map example.

As a reminder, the specific fields requested are in the excel file attached to the Trello card above

**Pull request merged**
